name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "899c28ccaf89e4573fb7b7ea44e023963e18e79a9fb09a038d94be35cb6a3e2b"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
