name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be18e51fac2a7ba2924b332848736232fd92cf09136dcb645c8ac4746fc0fe19"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
