name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5856c2237e1e9f853cae0e72602267441e79cc2da82e49ae73347dc35bbe8e7a"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
