name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deff350febc2805cda13c9369bba15811f23d595c66e029e591a72af4c44a191"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
