name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7add7730e6dccee0b2d03b2d4a10f1374f79b64410b5ad41838b60263e7c9979"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
