name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aef9d9f69cd376fd33ce4b670cad576f87432f0c41590e8c134f26f434fc3933"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
