name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15ed02afebd143c66a41c0bfca851531b2e860741ec11a757eb64344308d40ca"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
