name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5e909d3aee6994f79d3f9fce4f81718b9548c7609a96c2ba2681977283c16f"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
