name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e23336ca7c93e9b1215f37f77f635cda40e2f617ecf39b4b6f4ee5a43e61da67"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
