name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69b7035bf46de69c94f244e49b2268b044e52b00f5cfd47c94a9403fe9cc7d19"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
