name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ffb5adf7b2e57be7ae89677fbed2112d0dccf00203cfaf0ce224f323047c59c"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
