name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6563f2c98dfebacbea25450e6e67d6bcb204dac3b73d5979d1ac9b3a27a11f72"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
