name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51a1d1362020b291bbd8e9d9c6c90fffb7335bad3f620cc8227f9d2a331f0f16"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
