name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c4fdf38da033d7902c5815c460817b9db33e9fd0ba55243fb5bc22b35aeebc"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
