name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c126b84e0c864d1e69a8de814198744ef7a75111ee34b85eaf78cffa0cd9a5ed"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
