name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e926356a85d236ae9a67d74628a5f7445895febbc44be69b8ab60548d8149ded"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
