name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee9101d957b7bbfb73cc9bafe68b827b7f0628241bb92da7ea859e7bd5a784bd"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
