name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44887944bf0c250e341cffa4b055620574fa70de5dc39cd4f04be4ba30cfb58"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
