name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5a9285e85d1751fc66cb4484b0435361906bcfa8ad5280e9d323aca637124ff"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
