name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13b7e0432ee34c4b2862dfef68dd50632ce760985b56df5060b1ebc660222487"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
