name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98eb31b67731286518ed05953ea8b7a0ce0749686f0ed65fbbbdac6a307cbd22"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
