name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1015d423077424caf806ad8c86eb7ea5f880a44e77b9a3bbf3ea0311b9aed24"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
