name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4126d20452ed9c6dd79eb3bccc5a63d91f73e5d49bf993ee23f2702ff8548e9f"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
