name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee1ee1788812f687f02f7637a76f96edd716eab677c1b67e0b229a1d66bd5f67"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
