name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "336a9393d2dc3b290a1b7ade40367578d31dddd57a460e0e6b0ed4089eb6e9d5"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
