name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa422a751e5831509387814143fbfb40e4c3b4af3d3a32bccb7b3a478b9f4763"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
