name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5cdb25cdf5cdc79852e8a4c7efb522828b3849f8cf493a43a77fd8504ab6589"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
