name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e830080a7f5af12c7c476aa3eeb3a974ea50087887c28eb94532db652b4e8c0b"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
