name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edfc0b8616b73d49061e521981a3a31087615d5f4aad19ada71e9f1cc4507aa2"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
