name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c6865484532dbb2c0d74cc1a1b41051d1523b0cde186159b535171eec574bb4"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
