name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abad8f2de85cbe9a0e3d42652f2790df0b27b15b806e4b63812b45b24d6b594e"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
