name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25d2d663ea61fd3f09ae19ccba738225b6e8ce99173c5077ecc0f6640effdfce"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
