name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc6550838c70a4527ef396965c943ac2be21150102a3da6ae1b68c5eccca907b"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
