name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0805044b5e4024e1cfabac037763642390fcd78a783a86e7b129ed6fb08a52c"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
