name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ff3accaf50a1a8db034922ea5834749a6cfc1dbb573f91ff998922711a8cc5d"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
