name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e9d633c6acecd7067b1b1dc3f9f290af965909e2c668401b00a0cebf3eed071"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
