name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d13aec3387a3ad9d7946cbc5d1e165b0418a1d17324480b78f77bc8cfb9ce34"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
