name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c06bc4e085182d16361ff7d327632296fa37fbc6a14684eb913487dbaa9fc82"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
