name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4aa46f3c888230dd97804908fff07b176b7be58ea5cf983fd05a4815a577788"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
