name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "885476aaf1f5db717a3bce9457981bc0407478fd1bffb0007d1977a0c4b73a68"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
