name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ccfb1cce557509d1d6b2135f2559ed8b1a6713390f08f83add595b2a81c4c6a"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
