name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebcbdd181a540b793a404824c52baa309f15d949e2a816f18fa1c044d8d29bfe"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
