name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce50b128d6c0903a9b6633341273541eb3dc8c9153951d8f99e54da942efdfe7"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
