name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e275a9ccf5bf39b638f25f563248eafda96b9364aed9871b0e730b4e9eaeea42"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
