name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa96f71401b3bd8b879dc08d167f52fca0e507772683db55d4dd6a760b146207"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
