name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cc1cfce854eb4ddddddf031e70385c9ac4d7dc9d133b80ee2612e0572b33aa6"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
