name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721e039cc2d6f9fd6d555123bc4f2e5dfe72cff6d562054322fc8fee867ccffc"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
