name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5b255d614dfe80611c6bda59b9fb9fa76bf3d6f5c849210f2d8278c313a6b7e"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
