name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3610b6bfd09c7309c46b7a4510e9aa7bf17eabe98ad1e21e2343174152b043f3"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
