name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68735c14594a2a97b05bb3113bf1368c74fe6c5eeab29a7c2eaacffa2f2c99ad"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
