name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae7f4aa694aed4f45c9ab83d7a6fef123d88328762b4558859d4ad200304e2ab"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
