name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbbd2c6795c5677aa1c950cf5c4d90ddd8a900fe73a33916659d178ea3420ba5"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
