name = "Beri Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e6ea184f638ce2afe58e639f26892490f2103bc6e3dd61030cafc2817792e13"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
