
[common]

	[common.general]
		#Should the player be teleported to the overworld when they fall in the end?
		endVoidTeleport = true

	[common.predator]
		#Range: 0.2 ~ 5.0
		predatorHealthFactor = 1.0
		#Range: 0.5 ~ 10.0
		predatorDamageFactor = 1.0

		[common.predator.spawnChances]
			#Chance for predators to spawn from stars. Set to 0.0 to disable.
			#Range: 0.0 ~ 1.0
			starSpawnChance = 0.0
			#Range: 0 ~ 64
			maximum = 3
			#Set weight to 0 to disable spawning.
			#Range: 0 ~ 100
			weight = 0
			#Chance for predators to spawn when an animal dies. Set to 0.0 to disable.
			#Range: 0.0 ~ 1.0
			animalSpawnChance = 0.0
			#Range: 0 ~ 64
			minimum = 1

		[common.predator.spawnBiomes]
			#The predator can only spawn in biomes with the included types.
			include = ["FOREST", "PLAINS", "HILLS", "SWAMP", "SANDY", "SNOWY", "WASTELAND", "BEACH"]
			#The predator cannot spawn in biomes with excluded types.
			exclude = ["MOUNTAIN", "NETHER"]

