name = "Dragon Survival"
filename = "DragonSurvival-1.16.5-0.0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/631/DragonSurvival-1.16.5-0.0.38.jar"
hash-format = "murmur2"
hash = "1698027039"

[update]
[update.curseforge]
file-id = 3424631
project-id = 420799
release-channel = "beta"
