name = "Immersive Posts"
filename = "immersiveposts-1.16.5-4.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/142/immersiveposts-1.16.5-4.2.1.jar"
hash-format = "murmur2"
hash = "958909496"

[update]
[update.curseforge]
file-id = 3454142
project-id = 314645
release-channel = "beta"
