name = "MCDoom"
filename = "MCDoom-1.16.5-4.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/595/MCDoom-1.16.5-4.0.13.jar"
hash-format = "murmur2"
hash = "772505437"

[update]
[update.curseforge]
file-id = 3467595
project-id = 368765
release-channel = "beta"
