name = "Off Hand Combat"
filename = "OffHandCombat-1.16.3-3.2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3203/449/OffHandCombat-1.16.3-3.2.0.3.jar"
hash-format = "murmur2"
hash = "964557328"

[update]
[update.curseforge]
file-id = 3203449
project-id = 417112
release-channel = "beta"
