name = "THE UNDEAD"
filename = "UNDEADv.1.2c.release+biome.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3448/844/UNDEADv.1.2c.release+biome.jar"
hash-format = "murmur2"
hash = "686066575"

[update]
[update.curseforge]
file-id = 3448844
project-id = 479710
release-channel = "beta"
